export const cvData = {
  name: "SHAHBAZ AHMED",
  title: "App Developer",
  email: "shahbazahmed2001@outlook.com",
  phone: "0501185123",
  location: "Dubai, UAE",
  dob: "13 April 2001",
  summary:
    "Adaptable IT professional with a Bachelor's degree in Information Technology and hands-on experience in app development, system setup, and user support. Skilled in backend development (NestJS, TypeScript), AI/ML pipelines, and modern web technologies. Continuously improving technical knowledge with focus on efficient problem-solving.",
  workExperience: [
    {
      title: "App Developer (Internship)",
      company: "PureCS/Dawak",
      location: "Dubai, UAE",
      duration: "4 months (Recent)",
      highlights: [
        "Developed backend services using NestJS and TypeScript",
        "Built and maintained AI/ML pipelines for prescription OCR",
        "Integrated Docker for containerization and deployment",
        "Worked on digital pharmacy platform (PureHealth ecosystem)",
        "Collaborated with cross-functional teams on feature implementation",
      ],
    },
    {
      title: "Customer Service Associate",
      company: "PureHealth, Dubai Airport",
      location: "Dubai, UAE",
      duration: "09/2021 - 04/2022",
      highlights: [
        "Resolved customer complaints and identified problems",
        "Data entry and database management",
        "Created reports from system data",
      ],
    },
  ],
  education: [
    {
      degree: "Bachelor of Science in Information Technology",
      school: "Amity University",
      location: "Dubai, UAE",
      year: "09/2018 - 11/2022",
      courses: ["Web Development", "Python Programming", "Network Security", "Java Programming"],
    },
    {
      degree: "O Level (IGCSE)",
      school: "Grammar School",
      location: "Dubai, UAE",
      year: "09/2016 - 06/2018",
      courses: ["Economics", "Accounting"],
    },
  ],
  skills: {
    "AI & Automation": ["AI Tools", "Machine Learning Pipelines", "OCR/VLM", "Python"],
    "Web Development": ["Next.js", "React", "JavaScript", "TypeScript", "CSS", "HTML"],
    Backend: ["NestJS", "Node.js", "Python", "API Design"],
    DevOps: ["Docker", "Git", "Linux"],
    Data: ["Data Analysis", "Python", "SQL basics"],
    "Soft Skills": ["Problem Solving", "Creativity", "Communication", "Team Collaboration"],
  },
  languages: [
    { language: "Urdu", proficiency: "Native or Bilingual" },
    { language: "English", proficiency: "Full Professional" },
    { language: "Arabic", proficiency: "Limited Working" },
    { language: "Punjabi", proficiency: "Full Professional" },
  ],
  interests: [
    "Mindfulness",
    "Reading",
    "Peer Monitoring",
    "Volunteering",
    "Travelling",
    "Art",
    "Gaming",
    "Sports",
  ],
  github: "https://github.com/shabaz0077",
  aboutStory:
    "I grew up in Dubai and studied Information Technology at Amity University. The path into software was not a straight line: customer service at Dubai Airport taught me how people actually use systems, then the PureCS/Dawak internship let me build NestJS services and an OCR pipeline for a digital pharmacy. I like backend work, AI tooling, and shipping small live demos that prove an idea instead of only describing it.",
  homeTagline: "Backend services, AI tools, and small live demos that prove an idea.",
};

export const skillShowcase = [
  { name: "Next.js", group: "Frontend" },
  { name: "React", group: "Frontend" },
  { name: "TypeScript", group: "Frontend" },
  { name: "NestJS", group: "Backend" },
  { name: "Node.js", group: "Backend" },
  { name: "Python", group: "Backend" },
  { name: "OCR / VLM", group: "AI/ML" },
  { name: "Hugging Face", group: "AI/ML" },
  { name: "Docker", group: "DevOps" },
  { name: "Git", group: "DevOps" },
  { name: "Linux", group: "DevOps" },
  { name: "SQL", group: "Data" },
];
